# Generated by Django 4.1 on 2022-08-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_best',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
