# Generated by Django 4.1 on 2022-08-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_productes_recipeproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='intro',
            field=models.TextField(),
        ),
    ]
