# Generated by Django 4.1 on 2022-08-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='content',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='updated_at',
        ),
    ]
