# Generated by Django 4.1 on 2022-08-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_content_created_at_remove_content_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maincategory',
            table='main_categories',
        ),
        migrations.AlterModelTable(
            name='recipecommentlike',
            table='recipecomment_like',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='sub_categories',
        ),
    ]
