# Generated by Django 4.1 on 2022-08-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_maincategory_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomment',
            name='tag',
            field=models.BooleanField(),
        ),
    ]
