# Generated by Django 4.1 on 2022-08-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_subcategory_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='step',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
